import type { Tour } from 'nextstepjs'

export const ONBOARDING_TOURS: Tour[] = [
  {
    tour: 'tour_planning',
    steps: [
      {
        icon: null,
        title: 'Passo 3 — Seu planejamento',
        content: 'Ótimas notícias! Suas peças foram criadas. Aqui você gera seu primeiro plano de estudos automático.',
        selector: undefined,
        side: 'bottom',
        showControls: true,
      },
      {
        icon: null,
        title: 'Selecione o programa',
        content: 'O programa "Aulas Regulares" já foi criado com as suas peças. Marque-o para incluir no planejamento.',
        selector: '#onboarding-planning-programs',
        side: 'top',
        showControls: true,
        pointerPadding: 8,
      },
      {
        icon: null,
        title: 'Escolha o horizonte',
        content: 'Defina se quer planejar para 1 semana, quinzena ou mês. Para começar, uma semana é o ideal.',
        selector: '#onboarding-planning-horizon',
        side: 'top',
        showControls: true,
      },
      {
        icon: null,
        title: 'Gere o planejamento',
        content: 'Toque aqui para gerar suas tarefas automaticamente. Elas vão aparecer distribuídas em cards por dia da semana — você pode clicar em qualquer card para editar ou adicionar tarefas extras.',
        selector: '#onboarding-planning-generate',
        side: 'top',
        showControls: true,
      },
      {
        icon: null,
        title: 'Comece seu estudo com foco!',
        content: 'Depois de revisar o plano, toque em "Confirmar e Salvar" para guardar tudo. Suas tarefas aparecerão em "Hoje" a partir de agora. Bons estudos!',
        selector: undefined,
        showControls: true,
      },
    ],
  },
  {
    tour: 'tour_today',
    steps: [
      {
        icon: null,
        title: 'Navegar por dias',
        content: 'Use as setas para ver as tarefas de outros dias da semana.',
        selector: '#onboarding-today-nav',
        side: 'bottom',
        showControls: true,
      },
      {
        icon: null,
        title: 'Sua agenda do dia',
        content: 'Aqui ficam as tarefas de estudo. Cada item tem um tempo sugerido e está ligado a uma peça ou exercício.',
        selector: '#onboarding-today-tasks',
        side: 'top',
        showControls: true,
      },
      {
        icon: null,
        title: 'Opções da tarefa',
        content: 'O botão ⋮ em cada tarefa abre um menu com todas as ações: focar, mover para outro dia, trocar a peça, editar o tempo e mais.',
        selector: '#onboarding-today-task-menu',
        side: 'left',
        showControls: true,
        pointerPadding: 6,
      },
      {
        icon: null,
        title: 'Configurar o tempo do dia',
        content: 'Toque aqui para definir quantos minutos você tem disponíveis hoje. O tempo é redistribuído automaticamente entre as tarefas.',
        selector: '#onboarding-banner-timer',
        side: 'top',
        showControls: true,
        pointerPadding: 6,
      },
      {
        icon: null,
        title: 'Rebalancear o dia',
        content: 'Redistribui igualmente o tempo restante entre as tarefas ainda não concluídas — útil quando o plano ficou desequilibrado.',
        selector: '#onboarding-banner-rebalance',
        side: 'top',
        showControls: true,
        pointerPadding: 6,
      },
      {
        icon: null,
        title: 'Início rápido',
        content: 'Toque aqui para abrir o Pomodoro com as tarefas do dia já carregadas. Mais fácil de entrar no ritmo!',
        selector: '#onboarding-today-start-btn',
        side: 'top',
        showControls: true,
      },
      {
        icon: null,
        title: 'Adicionar tarefa',
        content: 'Quer estudar algo que não está no plano? Adicione uma peça ou exercício extra diretamente no seu dia.',
        selector: '#onboarding-banner-add',
        side: 'top',
        showControls: true,
        pointerPadding: 6,
      },
      {
        icon: null,
        title: 'Editar meu plano',
        content: 'Veja e edite todas as tarefas da semana num único lugar — mude durações ou remova itens sem sair da tela.',
        selector: '#onboarding-banner-edit-plan',
        side: 'top',
        showControls: true,
        pointerPadding: 6,
      },
    ],
  },
  {
    tour: 'tour_pomodoro',
    steps: [
      {
        icon: null,
        title: 'Cronômetro de estudos',
        content: 'O Pomodoro divide o estudo em ciclos de foco e pausas curtas. Escolha o ciclo que melhor se encaixa na sua sessão.',
        selector: '#onboarding-pomodoro-timer',
        side: 'bottom',
        showControls: true,
      },
      {
        icon: null,
        title: 'Ciclos disponíveis',
        content: 'Clássico (25/5), Longo (50/10), Curto (15/5) ou Livre — defina você mesmo o tempo de foco e pausa.',
        selector: '#onboarding-pomodoro-cycles',
        side: 'bottom',
        showControls: true,
      },
      {
        icon: null,
        title: 'Ao finalizar a sessão',
        content: 'Marque o que você praticou e avalie sua dificuldade. Isso ajuda o sistema a planejar melhor suas próximas semanas.',
        selector: '#onboarding-pomodoro-checklist',
        side: 'top',
        showControls: true,
      },
    ],
  },
  {
    tour: 'tour_repertoire',
    steps: [
      {
        icon: null,
        title: 'Seu repertório',
        content: 'Aqui você acompanha todas as suas peças e exercícios. Veja o progresso de cada item pelo anel colorido.',
        selector: '#onboarding-repertoire-tabs',
        side: 'top',
        showControls: true,
      },
      {
        icon: null,
        title: 'Checklist por peça',
        content: 'Expanda uma peça para ver o checklist detalhado. Cada item representa uma habilidade técnica a dominar.',
        selector: '#onboarding-repertoire-piece',
        side: 'top',
        showControls: true,
      },
    ],
  },
  {
    tour: 'tour_mode_select',
    steps: [
      {
        icon: null,
        title: 'Dois modos num só lugar',
        content: 'Como professor, você tem duas áreas: "Dar aula" para gerenciar seus alunos, e "Estudar" para cuidar do seu próprio repertório e planejamento.',
        selector: '#mode-select-cards',
        side: 'bottom',
        showControls: true,
        pointerPadding: 8,
      },
      {
        icon: null,
        title: 'Troque quando quiser',
        content: 'Não precisa sair do app para mudar de modo. Pelo menu dentro de qualquer tela você volta aqui e escolhe de novo.',
        selector: '#mode-select-switch-hint',
        side: 'top',
        showControls: true,
      },
    ],
  },
  {
    tour: 'tour_teacher',
    steps: [
      {
        icon: null,
        title: 'Seus alunos',
        content: 'Aqui ficam todos os seus alunos. Clique em um aluno para gerenciar peças, exercícios e programas.',
        selector: '#onboarding-teacher-students',
        side: 'bottom',
        showControls: true,
      },
      {
        icon: null,
        title: 'Peças e exercícios',
        content: 'Dentro do perfil de cada aluno, você adiciona peças com checklist personalizado e exercícios por categoria.',
        selector: '#onboarding-teacher-tabs',
        side: 'bottom',
        showControls: true,
      },
      {
        icon: null,
        title: 'Programas',
        content: 'Crie programas (recital, aulas regulares, exame…) para agrupar o repertório por contexto e prazo.',
        selector: '#onboarding-teacher-programs',
        side: 'bottom',
        showControls: true,
      },
      {
        icon: null,
        title: 'Planejamento automático',
        content: 'Com os programas prontos, use "Gerar Planejamento" para criar um plano de estudos semanal personalizado para o aluno.',
        selector: '#onboarding-teacher-plan-btn',
        side: 'top',
        showControls: true,
      },
    ],
  },
]
